### ISSUE TITLE
Incompatibility to Fixed Waterlogging

### ISSUE THREAD

**Issue by TheButterbrotMan** [KxmischesDomi/BoatContainer#11] opened 2022-04-03 15:44 UTC
https://bytebin.lucko.me/ICzGi81LUR

**Comment by DomiIRL** [comment] 2022-04-03 16:26
Fixed Waterlogging is experimental and is not working as intended. I stopped working on it and won't fix any issues releated to it at this time.

**Closed as completed by DomiIRL** 2022-04-03 16:26 UTC
